// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ0cFwavuS8o-7QNgUeS2V_DZW1_xpOWM',
    appId: '1:1064550563285:web:21d1eec998fe14bd8a915c',
    messagingSenderId: '1064550563285',
    projectId: 'articapital',
    authDomain: 'articapital.firebaseapp.com',
    storageBucket: 'articapital.firebasestorage.app',
    measurementId: 'G-XKWGZCQSDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9G1hxmmlA6DYyun6dellOk4L92dQHiow',
    appId: '1:1064550563285:android:ff3d0fd9410999978a915c',
    messagingSenderId: '1064550563285',
    projectId: 'articapital',
    storageBucket: 'articapital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh4EjkeWBaCveWjmQBPzamMgMAKjzdT8U',
    appId: '1:1064550563285:ios:51cf52d7487a81108a915c',
    messagingSenderId: '1064550563285',
    projectId: 'articapital',
    storageBucket: 'articapital.firebasestorage.app',
    iosBundleId: 'com.office701.articapital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh4EjkeWBaCveWjmQBPzamMgMAKjzdT8U',
    appId: '1:1064550563285:ios:b892beeb5edb7b708a915c',
    messagingSenderId: '1064550563285',
    projectId: 'articapital',
    storageBucket: 'articapital.firebasestorage.app',
    iosBundleId: 'com.example.artiCapital',
  );
}
